esp_err_t set_timer(void);
esp_err_t FSM(void);
esp_err_t Select_line(void);
esp_err_t Enter(void);
esp_err_t Go_to_back(void);
esp_err_t configure_manual_settings(void);
esp_err_t set_ADC(void);
void setTemp(float temperature);
void setHum(float humid);
void setTankLevel(float tank);
void setSoilhumidity(int soil);